export const SEND_MOVIE_UPDATING_REQUEST = "admin/SEND_MOVIE_UPDATING_REQUEST";
export const SEND_MOVIE_UPDATING_SUCCESS = "admin/SEND_MOVIE_UPDATING_SUCCESS";
export const SEND_MOVIE_UPDATING_FAIL = "admin/SEND_MOVIE_UPDATING_FAIL";

export const POST_MOVIE_REQUEST = "admin/POST_MOVIE_REQUEST";
export const POST_MOVIE_SUCCESS = "admin/POST_MOVIE_SUCCESS";
export const POST_MOVIE_FAIL = "admin/POST_MOVIE_FAIL";

export const GET_MOVIE_REQUEST = "admin/GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "admin/GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "admin/GET_MOVIE_FAIL";
