export const GET_MOVIE_DETAIL_REQUEST = "all/GET_MOVIE_DETAIL_REQUEST";
export const GET_MOVIE_DETAIL_SUCCESS = "all/GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAIL = "all/GET_MOVIE_DETAIL_FAIL";
