export const ACT_UPDATE_INFOR_REQUEST = "ACT_UPDATE_INFOR_REQUEST";
export const ACT_UPDATE_INFOR_SUCCESS = "ACT_UPDATE_INFOR_SUCCESS";
export const ACT_UPDATE_INFOR_FAIL = "ACT_UPDATE_INFOR_FAIL";

export const ACT_UPDATE_PASSWORD_REQUEST = "ACT_UPDATE_PASSWORD_REQUEST";
export const ACT_UPDATE_PASSWORD_SUCCESS = "ACT_UPDATE_PASSWORD_SUCCESS";
export const ACT_UPDATE_PASSWORD_FAIL = "ACT_UPDATE_PASSWORD_FAIL";
