export const GET_SCHEDULE_MOVIE_REQUEST = "GET_SCHEDULE_MOVIE_REQUEST";
export const GET_SCHEDULE_MOVIE_SUCCESS = "GET_SCHEDULE_MOVIE_SUCCESS";
export const GET_SCHEDULE_MOVIE_FAIL = "GET_SCHEDULE_MOVIE_FAIL";
