export const GET_MOVIE_TRAILER_SOURCE_REQUEST =
  "GET_MOVIE_TRAILER_SOURCE_REQUEST";
export const GET_MOVIE_TRAILER_SOURCE_SUCCESS =
  "GET_MOVIE_TRAILER_SOURCE_SUCCESS";
export const GET_MOVIE_TRAILER_SOURCE_FAIL = "GET_MOVIE_TRAILER_SOURCE_FAIL";
