export const GET_TICKET_ROOM_REQUEST = "GET_TICKET_ROOM_REQUEST";
export const GET_TICKET_ROOM_SUCCESS = "GET_TICKET_ROOM_SUCCESS";
export const GET_TICKET_ROOM_FAIL = "GET_TICKET_ROOM_FAIL";

export const ACT_BOOKING_TICKET_SUCCESS = "ACT_BOOKING_TICKET_SUCCESS";
